package TutorialIsland;

import org.dreambot.api.methods.Calculations;
import org.dreambot.api.methods.widget.Widgets;
import org.dreambot.api.script.TaskNode;

public class TutorialIslandAppearance extends TaskNode {
    private int rando;
    private int gender;
    String widgey = Widgets.getWidget(263).getChild(1).getChild(0).getText();
    @Override
    public boolean accept() {
        return false;
    }

    @Override
    public int execute() {
        log("Tutorial appearance");
        if (widgey.contains("Setting your appearance")) {
            switch (rando = Calculations.random(1, 9)) {
                case 1:
                    Widgets.getWidget(679).getChild(12).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(65).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(17).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(20).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(60).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(66).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 2:
                    Widgets.getWidget(679).getChild(51).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(56).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(32).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 3:
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(25).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(55).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(66).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(66).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 4:
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(25).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(55).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(66).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(32).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(32).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(32).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(16).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(16).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(37).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(37).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(37).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 5:
                    Widgets.getWidget(679).getChild(12).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(12).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(12).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(16).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(21).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(21).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(21).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(60).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(60).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(60).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(33).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(33).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(24).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(24).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(24).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(24).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(36).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(37).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(37).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(44).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(66).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 6:
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(28).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(28).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(47).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(47).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(47).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(47).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(29).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(29).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(51).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(51).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(51).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(55).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(55).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(55).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(65).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 7:
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(25).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(55).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(66).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 8:
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(43).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(21).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(21).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(21).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(66).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 9:
                    Widgets.getWidget(679).getChild(36).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(32).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(29).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(44).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(44).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(65).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
                case 10:
                    Widgets.getWidget(679).getChild(28).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(32).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(32).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(59).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(66).interact("Select");
                    sleep(500);
                    Widgets.getWidget(679).getChild(68).interact("Confirm");
                    sleep(5000);
                    new TutorialIsland().onLoop();
                    sleep(10000);
                    break;
            }}else {
            new TutorialIsland().onLoop();
            sleep(10000);
        }
        return 0;
    }
}
